### ISSUE TITLE
load_interproscan_matches with --cpu > 1 generates error and multiple 'multispecies' organisms entries are also created

### ISSUE THREAD

**Issue by mmudado** [lmb-embrapa/machado#236]
### Setup

Python version: 
Operating system:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

**Comment by azneto** [comment]
Registering the organism 'multispecies' during the initial database setup (migrate) will ensure the command will not create duplicate entries when using multiple threads
