### ISSUE TITLE
remove_analysis does not remove fille when full path is entered

### ISSUE THREAD

**Issue by mmudado** [lmb-embrapa/machado#237]
if one enters a name of a file with its full path (with directories), the tool does not remove the file and the analysis

### Setup

Python version: 
Operating system:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

**Comment by mmudado** [comment]
In fact, the command always return "Done." even if the filename does not exist.

**Comment by azneto** [comment]
remove_analysis fixed to raise error if the file is not registered
