### ISSUE TITLE
JBrowse default tracks should be in settings.py instead of inside feature.py code

### ISSUE THREAD

**Issue by mmudado** [lmb-embrapa/machado#262]
Suggestion: JBrowse default tracks should be in settings.py for user to configure instead of inside /views/feature.py code

### Setup

Python version: 
Operating system:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

**Comment by azneto** [comment]
It's ready. Don't forget to close this issue after you test it.
