### ISSUE TITLE
export search results for PUFs to .tsv file (Protocol D)

### ISSUE THREAD

**Issue by marcosjviana** [lmb-embrapa/machado#270]
### Expected behaviour

Export with all fields displayed in the bowser.

### Actual behaviour

Organism field is not exported to the .tsv file.

**Comment by azneto** [comment]
@marcosjviana, the export tool was fixed to export the organism data. Please, check this update and close the issue if it done.

**Comment by marcosjviana** [comment]
34/5000
Resolved, Thank you!
