### ISSUE TITLE
Species scientific names should be displayed in italic 

### ISSUE THREAD

**Issue by mmudado** [lmb-embrapa/machado#281]
### Setup

Python version: 
Operating system:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

**Comment by azneto** [comment]
The commit https://github.com/lmb-embrapa/machado/commit/c0c5e024efc9697938cf58d84ddec5565897a093 addressed this issue
