### ISSUE TITLE
Create API to retrieve all information from feature page for a given feature_id

### ISSUE THREAD

**Issue by mmudado** [lmb-embrapa/machado#282]
### Setup

Python version: 
Operating system:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

**Comment by mmudado** [comment]
To be more specific, I was thinking of feature/functional_annotation e feature/similarity

**Comment by azneto** [comment]
@mmudado, the endpoints to retrieve ontology and similarity are ready:
https://www.machado.cnptia.embrapa.br/demo_machado/api/

Please, check it out and close the issue if it's done.

**Comment by azneto** [comment]
Closing this because it's inactive for more than 15 days. Feel free to open another one if you find any problems.
