### ISSUE TITLE
Dúvida - Transcriptomas

### ISSUE THREAD

**Issue by fabianomenegidio** [lmb-embrapa/machado#294]
Parabéns pelo trabalho, um ótimo acréscimo a comunidade nacional de Bioinformática. Estava pensando em usar o Tripal em um projeto, mas estou testando o Machado.

Tenho uma dúvida. Consigo subir um transcriptoma para ele ao invés de um genoma?

Att

**Comment by azneto** [comment]
Obrigado, Fabiano. Espero que o Machado seja útil para você. 
Normalmente os dados carregados no Chado são mapeados em um genoma de referência, nós nunca fizemos testes com um transcriptoma de referência. Em teoria, deve funcionar. 

Na etapa de carregar a sequência de referência (https://machado.readthedocs.io/en/latest/load_fasta.html) você pode selecionar --soterm assembly ou algum outro termo da ontologia de sequências (http://www.sequenceontology.org/browser/obob.cgi), como contig ou mRNA_contig. 

Nos informe sobre o seu progresso e se tiver problemas em alguma etapa da construção do seu banco de dados.

**Comment by fabianomenegidio** [comment]
Fechando esse.
