### ISSUE TITLE
Gene ontology

### ISSUE THREAD

**Issue by aussieEd** [lmb-embrapa/machado#300]
Hi There,

I'm keen to try out what I think will be a fantastic piece of software. I'm trying to set it up now but have come accross an error that I am hoping you can help with.

Following the instruction I am up to 2.1.3. Gene ontology. I have downloaded the relevant go.obo and run the following command:
`python manage.py load_gene_ontology --file go.obo`

I obtain the following error message:

> (project_env) root@t:/var/www/machado/machado_web# python manage.py load_gene_ontology --file go.obo
> Preprocessing
> Loading typedefs (1 threads)
> 0it [00:00, ?it/s]
> Loading terms (1 threads)
>  66%|██████████████████████████████████████████████████████▎                           | 3872/5851 [01:58<01:00, 32.59it/s]
> Traceback (most recent call last):
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/machado-0.3.0-py3.8.egg/machado/loaders/ontology.py", line 232, in store_term
>     name=data["name"],
> KeyError: 'name'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     main()
>   File "manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/machado-0.3.0-py3.8.egg/machado/management/commands/load_gene_ontology.py", line 88, in handle
>     if task.result():
>   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
>     raise self._exception
>   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/machado-0.3.0-py3.8.egg/machado/loaders/ontology.py", line 239, in store_term
>     raise ImportingError("{}\nError loading {}".format(e, data))
> machado.loaders.exceptions.ImportingError: 'name'
> Error loading {}

Any ideas on what could be causing this issue?

**Comment by azneto** [comment]
Hi!
I've just tested the GO loader using python3.8 and the latest go.obo file from http://current.geneontology.org/ontology/go.obo and it worked. 

The log you provided shows that no typedefs were loaded and the number of terms is very different from what I've got.

```
python manage.py load_gene_ontology --file /home/adhemar/Downloads/go.obo --cpu 4
Preprocessing
Loading typedefs (4 threads)
100%|███████████████████████████████████████████████████████| 10/10 [00:00<00:00, 159.15it/s]
Loading terms (4 threads)
100%|██████████████████████████████████████████████████| 44085/44085 [12:16<00:00, 59.87it/s]
Loading relationships (4 threads)
100%|█████████████████████████████████████████████████| 90442/90442 [05:05<00:00, 296.34it/s]
Done

```


What is the MD5 of the file you're trying to load?

$ md5sum go.obo
093c97951359558c45f216ee4a222374  go.obo

**Comment by aussieEd** [comment]
@azneto thanks for taking time out to reply to my question. You were absolutely correct. The issue was a corrupt go.obo file (out by one byte). Thanks for helping and geting me past this firest step... now on to loading the taxonomy files.
