### ISSUE TITLE
Changing the template

### ISSUE THREAD

**Issue by aussieEd** [lmb-embrapa/machado#301]
Hi There,

We now seem to have our data loaded into Machado which is great. I was all set to make some changes to the home screen and header as I don't really want demo plastered all over the home page and it now has data and I suppose it's not really a demo any more. 

The problem I have is that the main app folder doesn't have any of the template files in it, but rather they are seemingly located in the 'src' folder. But when I make changes to any of these files the changes are not reflected on the webserver side... Even new files added to the "static" folder are not accessible through the browser suggesting that the templates are not retrieved from the subfolders in the 'src' directory.... So I guess my question is... where are the template files I need to edit or how can I get changes in the 'src' to be reflected in the webserver.

Thank you for your help and sorry if this question is obvious or seems a little silly.

Ed

**Comment by azneto** [comment]
Hi Ed, 
I'm glad to hear it's working out for you, so far. 
This is a great question.

We haven't managed to develop a local templates folder in order to simplify modifications to the website. 
The way we're dealing with it in our databases is to simply fork the Machado repository and edit the template files. 

One advantage of having your own repository is to freeze the code you've used to load the data. 
For the future versions of your database, you can run a git fetch upstream and merge the version you've used to the new code that would have been release. 

Cheers,
Adhemar

**Comment by azneto** [comment]
We're forking it to a local gitlab, but github is a nice option as well, since it now provides free private repos.

**Comment by azneto** [comment]
If you have a better solution in mind, a pull request is always welcome.

**Comment by aussieEd** [comment]
Thank so much for the great support Adhemar!

Running those commends I get the below errors. And static files added to `/var/www/machado/src/machado/machado/static` don't seem to be available. But edits made to the template do seem to be reflected on the webserver now.

Thanks again for the help.

`python manage.py collectstatic`

> You have requested to collect static files at the destination
> location as specified in your settings.
> 
> This will overwrite existing files!
> Are you sure you want to do this?
> 
> Type 'yes' to continue, or 'no' to cancel: yes
> Traceback (most recent call last):
>   File "/var/www/machado/machado_web/manage.py", line 22, in <module>
>     main()
>   File "/var/www/machado/machado_web/manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
>     collected = self.collect()
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
>     handler(path, prefixed_path, storage)
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 345, in copy_file
>     if not self.delete_file(path, prefixed_path, source_storage):
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 255, in delete_file
>     if self.storage.exists(prefixed_path):
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/core/files/storage.py", line 311, in exists
>     return os.path.exists(self.path(name))
>   File "/var/www/envs/project_env/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 38, in path
>     raise ImproperlyConfigured("You're using the staticfiles app "
> django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.


`python manage.py clear_cache`

> Unknown command: 'clear_cache'. Did you mean clear_index?
> Type 'manage.py help' for usage.

**Comment by azneto** [comment]
Your static directory should be inside the webapp directory and you need to set the variables STATIC_ROOT and STATIC_URL in the settings.py file. 

The documentation about configuring the webserver contains information related to static files: 
https://machado.readthedocs.io/en/latest/webserver.html

The cache is really optional: 
https://machado.readthedocs.io/en/latest/cache.html

**Comment by azneto** [comment]
Inactive for more than 10 days.
