### ISSUE TITLE
Issue while loading data into the database

### ISSUE THREAD

**Issue by guff95** [lmb-embrapa/machado#333]
### Setup

Python version: 3.8.12
Operating system: Linux

python 3.8.12 (default, Sep 10 2021, 00:16:05) 
[GCC 7.5.0]
CPython
Linux-5.4.0-91-generic-x86_64-with-glibc2.27

### Issue
when trying to run manage.py runserver it is also working fine. But when I try to load 
the fasta file into the database with the command
python manage.py load_fasta --file organism_chrs.fa --soterm chromosome --organism 'Arabidopsis thaliana'
it shows error

     self.cvterm_contained_in = Cvterm.objects.get(
     File "/home/guffi/Documents/projects/whole_genome_ingestion/machado_main/env_mogambo/lib/python3.8/site-packages    /Django-3.2.10-py3.8.egg/django/db/models/manager.py", line 85, in manager_method
      return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/home/guffi/Documents/projects/whole_genome_ingestion/machado_main/env_mogambo/lib/python3.8/site-packages  /Django-3.2.10-py3.8.egg/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist( machado.models.DoesNotExist: Cvterm matching query does not exist.)

I tried to do migrations but it shows

    return executor(sql, params, many, context)
    File "/home/guffi/Documents/projects/whole_genome_ingestion/machado_main/env_mogambo/lib/python3.8/site-packages/Django- 3.2.10-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
     File "/home/guffi/Documents/projects/whole_genome_ingestion/machado_main/env_mogambo/lib/python3.8/site-packages/Django-3.2.10-py3.8.egg/django/db/utils.py", line 90, in __exit__
      raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/home/guffi/Documents/projects/whole_genome_ingestion/machado_main/env_mogambo/lib/python3.8/site-packages   /Django-3.2.10-py3.8.egg/django/db/backends/utils.py", line 82, in _execute
      return self.cursor.execute(sql)
      django.db.utils.ProgrammingError: relation "acquisition" already exists

#####
Please help to solve this issue

**Comment by azneto** [comment]
This error indicates the soterm chromosome is not loaded to the database.
Have you loaded the ontologies?

Em sex., 7 de jan. de 2022 03:59, guff95 ***@***.***>
escreveu:

**Comment by guff95** [comment]
Thank you for the prompt response the issue that I faced was solved however, I have got one more issue. I loaded all the files Ontologies, Taxonomy, Organism into the database and also loaded new data however while connecting haystack with elastic search. The connection is successful but the rebuild index is not able to load data from database to the elasticsearch.
     `python manage.py rebuild_index`
     `Indexing 0 features`
Rebuild index is not populating the elastic search
@azneto

**Comment by azneto** [comment]
The index contains only features. Have you already loaded GFF files?

Em sex., 14 de jan. de 2022 às 07:47, guff95 ***@***.***>
escreveu:

**Comment by syedgufran95** [comment]
no I have just added above three things and sample fasta files present in the project.

**Comment by azneto** [comment]
OK. After loading some features, the rebuild_index will index them.

Em sex., 14 de jan. de 2022 às 10:03, syedgufran95 ***@***.***>
escreveu:

**Comment by azneto** [comment]
The 'extras' folder contains a few sample files:
https://github.com/lmb-embrapa/machado/tree/master/extras

Em sex., 14 de jan. de 2022 às 13:31, syedgufran95 ***@***.***>
escreveu:

**Comment by syedgufran95** [comment]
this zip doesn't has the feature file(.tb) @azneto

**Comment by azneto** [comment]
The feature files are the GFF3 ones. You should observe that it's required
to have a matching FASTA file loaded before the GFF3.

Em sex., 14 de jan. de 2022 às 15:52, syedgufran95 ***@***.***>
escreveu:

**Comment by guff95** [comment]
Great !!! everything is loaded fine. I am not able to view the data through the jbrowse viewer although I am able to get data through jbrowse API.  @azneto

**Comment by ayazwani** [comment]
Yes I'm also facing the same issue. JBROWSE is not displaying genomes, its showing something like this: <br> 
![jb](https://user-images.githubusercontent.com/26644055/149715459-6cbf04e7-bac1-4fca-9fb8-10d5ad69b2a7.png) whereas on demo application it shows something like this <br> 
![jb2](https://user-images.githubusercontent.com/26644055/149715809-760d39a2-71e8-4d2c-83d7-08e30e988eee.png)

**Comment by azneto** [comment]
JBrowse only shows the chromosome data of regions up to 1kbp. If you hold CTRL and double click, it will zoom in and eventually show the sequence. You can also click 'Full-screen view' to access better navigation tools.

**Comment by azneto** [comment]
Inactive for more than 10 days
