### ISSUE TITLE
RefSeqs JBrowse route is unusably slow with a large number of sequences

### ISSUE THREAD

**Issue by njbooher** [lmb-embrapa/machado#345]
### Setup

```
>>> import sys; print(sys.version)
3.8.8 (default, Aug 11 2021, 06:52:42) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.14.9-200.fc34.x86_64-x86_64-with-glibc2.2.5
```

### Expected behaviour

JBrowse on this page should load within a couple seconds
https://db.abalone.dbgenome.org/feature/?feature_id=1224439

### Actual behaviour
 JBrowse doesn't load because the RefSeqs api endpoint takes too long to load

From what I understand this is likely caused by ModelSerializer being slow.

https://hakibenita.com/django-rest-framework-slow

I will be testing the suggestions from that post today and probably make a pull request.

**Comment by azneto** [comment]
Performance upgrades are really welcome. Thanks.
