### ISSUE TITLE
Error step 20/36

### ISSUE THREAD

**Issue by gledisonteixeira** [lmb-embrapa/machado#350]
Caro, consegue me ajudar o que preciso configurar para passar deste erro?

Step 20/36 : RUN pip install git+${MACHADO_SOURCE}
 ---> Running in e24bbda46ec2
Collecting git+https://github.com/lmb-embrapa/machado.git
  Cloning https://github.com/lmb-embrapa/machado.git to /tmp/pip-req-build-6ctxwxa8
  Running command git clone --filter=blob:none -q https://github.com/lmb-embrapa/machado.git /tmp/pip-req-build-6ctxwxa8
  Resolved https://github.com/lmb-embrapa/machado.git to commit 5b042ff4e27df0d6b27a3a9aabd1929ca67858d3
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting bibtexparser==1.2.0
  Downloading bibtexparser-1.2.0.tar.gz (46 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting biopython==1.79
  Downloading biopython-1.79-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.3 MB)
Collecting django-haystack==3.2.1
  Downloading django-haystack-3.2.1.tar.gz (466 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting djangorestframework==3.13.1
  Downloading djangorestframework-3.13.1-py3-none-any.whl (958 kB)
Collecting django~=3.2.14
  Downloading Django-3.2.15-py3-none-any.whl (7.9 MB)
Collecting drf-nested-routers==0.93.4
  Downloading drf_nested_routers-0.93.4-py2.py3-none-any.whl (35 kB)
Collecting drf-yasg==1.20.0
  Downloading drf_yasg-1.20.0-py2.py3-none-any.whl (1.6 MB)
ERROR: Could not find a version that satisfies the requirement networkx==2.7.1 (from machado) (from versions: 0.34, 0.35, 0.35.1, 0.36, 0.37, 0.99, 1.0rc1, 1.0, 1.0.1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.4rc1, 1.4, 1.5rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.9rc1, 1.9, 1.9.1, 1.10rc2, 1.10, 1.11rc1, 1.11rc2, 1.11, 2.0, 2.1, 2.2rc1, 2.2, 2.3rc3, 2.3rc4, 2.3, 2.4rc1, 2.4rc2, 2.4, 2.5rc1, 2.5, 2.5.1)
ERROR: No matching distribution found for networkx==2.7.1
1 error occurred:
        * Status: The command '/bin/sh -c pip install git+${MACHADO_SOURCE}' returned a non-zero code: 1, Code: 1

Creio que seja bobagem minha,

obrigado

Gledison

**Comment by gledisonteixeira** [comment]
~/machado-docker$ id
uid=1002(machado) gid=1002(machado) groups=1002(machado),999(docker)

 cat .env
UID=1002
USER=machado
POSTGRES_DB=machadosample
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
MACHADO_SOURCE=https://github.com/lmb-embrapa/machado.git
MACHADO_PROJECT=machadosample


segue configuração ds variaveis

**Comment by azneto** [comment]
Gledison,
Ocorreram atualizações no machado que impossibilitam utilizar o python 3.6. 
Pelo jeito, você está executando o docker e a configuração do docker-compose ainda precisa ser atualizada. Vamos dar início ao processo de atualização do machado-docker e te aviso assim que estiver pronto. Como essa issue se refere a outro repositório do github, vou fechá-la e você pode abrí-la em https://github.com/lmb-embrapa/machado-docker para que eu possa te comunicar a conclusão do processo de atualização.

**Comment by gledisonteixeira** [comment]
claro, abro outra la, mas consigo ainda instalar ele?
